apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karma
  namespace: monitoring
spec:
  chart:
    spec:
      chart: charts/monitoring/karma
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
