kubermaticOperator:
    image:
        tag: v2.19.0
dex:
    ingress:
        host: michal-kkp-gce-gh.lab.kubermatic.io
    certIssuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    env:
        - name: KUBERNETES_POD_NAMESPACE
          value: oauth
    staticPasswords:
        - email: michal@kubermatic.com
          hash: ENC[AES256_GCM,data:rTKmFD+v4GKgp1rfA71aH6KK7iXPNaeqMIho3zlsNb/4JUFtxScbQbVgPRA+CiCa8JhSTynrff+Zm849,iv:8FGvrKDVPpTHkyvXasJYQ+pke3guSzH5899Rs6ssVqQ=,tag:R6wqBB0iNY3VUG26t8rkng==,type:str]
          username: michal@kubermatic.com
          userID: 33b2f203-1bf2-4559-9cba-ed76dab5afb6
    clients:
        - id: kubermatic
          name: Kubermatic
          secret: ENC[AES256_GCM,data:br87F4RYeKIl1yv2Ps3wqLIbyJmoLlm9d1RkAf8ur5k=,iv:055zfHCwojkEXCEJuKhAS89sjQ+3NJPfNfXd+xEKPv4=,tag:1XR0fjlPsdSRn84e5KRu9Q==,type:str]
          RedirectURIs:
            - https://michal-kkp-gce-gh.lab.kubermatic.io
            - https://michal-kkp-gce-gh.lab.kubermatic.io/projects
        - id: kubermaticIssuer
          name: Kubermatic OIDC Issuer
          secret: ENC[AES256_GCM,data:joqUDflowVug5APH2ayhyg==,iv:V2IvcrHM0owNUkBkkEGhGOygbPyjjVTtD08DyGzFQKQ=,tag:F8/jwVKE4gUUgY3SNbqHMA==,type:str]
          RedirectURIs:
            - https://michal-kkp-gce-gh.lab.kubermatic.io/api/v1/kubeconfig
        - id: prometheus
          name: Prometheus
          secret: ENC[AES256_GCM,data:leVAFyP58gQKufFnQUlFNA==,iv:jdJrnvXaB7mohmm/Z+iMDNSMGvtikbaU3Oh3F6lbLLs=,tag:jPTFOnl++QrcNtV0CWrFWw==,type:str]
          RedirectURIs:
            - https://prometheus.michal-kkp-gce-gh.lab.kubermatic.io/oauth/callback
        - id: alertmanager
          name: Alertmanager
          secret: ENC[AES256_GCM,data:wpUYCxEWL88dc2mkjxEBLg==,iv:4CxmUymuI5cUIVUGLx1nBVEtFoRmHPimOKtLLfIfT2Y=,tag:ojU/9SWkrU3/6WTPdRWKdA==,type:str]
          RedirectURIs:
            - https://alertmanager.michal-kkp-gce-gh.lab.kubermatic.io/oauth/callback
        - id: grafana
          name: Grafana
          secret: ENC[AES256_GCM,data:8I0WcCag6h0tqMhuAE9kbw==,iv:/NtdqaxsTSM1pxRkSsfRTs592J9/wOMdFFwg4cwrDqc=,tag:pymXM79LVu5nccAA3Sy3kA==,type:str]
          RedirectURIs:
            - https://grafana.michal-kkp-gce-gh.lab.kubermatic.io/oauth/callback
        - id: karma
          name: Karma
          secret: ENC[AES256_GCM,data:WmRoeAKj2dvzjcOYid3AEQ==,iv:KAFaFsZxvnZqCEZuGrQPZ72mAivOt9qRaTFIUi9VUq8=,tag:cyOTi1XhLB3flg677ZR85w==,type:str]
          RedirectURIs:
            - https://karma.michal-kkp-gce-gh.lab.kubermatic.io/oauth/callback
alertmanager:
    host: alertmanager.michal-kkp-gce-gh.lab.kubermatic.io
grafana:
    user: admin
    password: ENC[AES256_GCM,data:GQ5ejggQ3gE/vpEZjsLgyw==,iv:sE3hG2AY0REA1/9QDGIXtt+zohi1QAKOSPizffOJEnc=,tag:FjEVBCVyU91cK7Mzk4m38g==,type:str]
    provisioning:
        configuration:
            auto_assign_org_role: Editor
            disable_login_form: false
            root_url: https://grafana.michal-kkp-gce-gh.lab.kubermatic.io
        datasources:
            lokiServices:
                - loki
prometheus:
    host: prometheus.michal-kkp-gce-gh.lab.kubermatic.io
    storageSize: 125Gi
    tsdb:
        retentionTime: 7d
    ruleFiles:
        - /etc/prometheus/rules/general-*.yaml
        - /etc/prometheus/rules/kubermatic-*.yaml
        - /etc/prometheus/rules/managed-*.yaml
iap:
    oidc_issuer_url: https://michal-kkp-gce-gh.lab.kubermatic.io/dex
    deployments:
        prometheus:
            name: prometheus
            ingress:
                host: prometheus.michal-kkp-gce-gh.lab.kubermatic.io
            upstream_service: prometheus.monitoring.svc.cluster.local
            upstream_port: 9090
            client_id: prometheus
            client_secret: ENC[AES256_GCM,data:I15YO+T5UszJcKrQt9cB0Q==,iv:xD6ezaLIt4jqSnKZjqtCfKW3RQmI7Y8YNUbuFreoGgs=,tag:kjTpvOvadCXxCdYPgqGxjw==,type:str]
            encryption_key: ENC[AES256_GCM,data:okemouneamLWTH2ohmlupCa+gi4Nf5BESPzEIzze9AM=,iv:FiDGhfaM0RCFBYAKXoOX6U/44Be3sO20MHxop5ODxQA=,tag:uQoWeQbdTJlxe2K6QBkclQ==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        alertmanager:
            name: alertmanager
            ingress:
                host: alertmanager.michal-kkp-gce-gh.lab.kubermatic.io
            upstream_service: alertmanager.monitoring.svc.cluster.local
            upstream_port: 9093
            client_id: alertmanager
            client_secret: ENC[AES256_GCM,data:VlULCsYLWOCk8Opag6z9XQ==,iv:sDLIbbWWbp07Ap/DaH9m9Wt05yW5mDUX0eoPQjwha5I=,tag:qZy1uo+ptF2l4X+s1XM1cg==,type:str]
            encryption_key: ENC[AES256_GCM,data:zx8bu1q89sL2w3Y4LuZHqb84JlxDHTC8L0pVLWu0ijo=,iv:RHTumhDb9RGZThuVNvjm9CudzbQcO55yzkzRuUjqJ7s=,tag:SnlQ393imBHlxGPgqJvAmQ==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        grafana:
            name: grafana
            ingress:
                host: grafana.michal-kkp-gce-gh.lab.kubermatic.io
            upstream_service: grafana.monitoring.svc.cluster.local
            upstream_port: 3000
            client_id: grafana
            client_secret: ENC[AES256_GCM,data:/O2vqhjwWrVSnMmsCFL9pA==,iv:C7SLvhJnhukQgRRa7Kh2vAymHlVKQzl9tmRP9XivwSQ=,tag:BMVgqF661mlUhtCNDDLNdA==,type:str]
            encryption_key: ENC[AES256_GCM,data:hOtRAGLU65o+5nlHcRGR52wBeMgaflAhLR1SBRQijNo=,iv:2IToQKsU6q3vOkSFl1ozp0s2f8wU0hiznBi6lFq6eWc=,tag:eYC/Oq570mWafcKpn+FjAw==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /api/health
        karma:
            name: karma
            ingress:
                host: karma.michal-kkp-gce-gh.lab.kubermatic.io
            upstream_service: karma.monitoring.svc.cluster.local
            upstream_port: 8080
            client_id: karma
            client_secret: ENC[AES256_GCM,data:212JXJ1pNaSqcusDUXQz7w==,iv:NTcuFZY0X1p5TbHyqaZxg8x7lfwQ1ylUrcTud0bGJBA=,tag:MQdoYwJpwZXZ6XY1bXIjdw==,type:str]
            encryption_key: ENC[AES256_GCM,data:9UDAkKjT+ZPlMd8EP8fDPlQoswF9KVt4LaAHJopYAfQ=,iv:vYwR8cv8vPqfMuSHc3VRTPin5jWrsnBSF1s+OhT65r0=,tag:KwK+Srh126xUJxNxSwrZ/g==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
telemetry:
    # uuid is the unique identifier of the client where the agent is running.
    # This field is required and will print an error message when that entry is missing.
    uuid: a767f1f3-b663-4470-9b7d-a1fa90d469cd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lf2ddxlw3tx2598heceqdgnkn9zdnfeuxj57gpmqzaj67wpndg9qqle3d8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBempoU0ZWVFNUczNkZ2RY
            Zm56RWxmRG8xbTQvei9FaE9LdWtUZVpOVUQwCmNKbGd3RU92cDZ3emlMcGxHVE5a
            dE1QRWc3RWRNZVlyNUJMakFldjRTa0kKLS0tIGxBZ0pXZHk3cFZUV3psdjZqanlY
            M0E5OHJnTy8rNEZsS1F6WmNhRmdlTkEKvarmsiJMobeedz2SQgNB6l3+U+Lapvf1
            vnWX2o8uCOwvsgB0nhE7XmQdHfW5Ma2EzyeCkhVXo3tLKDMR7yOiTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-23T11:42:13Z"
    mac: ENC[AES256_GCM,data:pXlW5RAzMVX+3LorKnkOWjEq7X/52+zMTHTXQCHHjv1AepIdJMNtUlRcq3t1WEaWuTJwBERhuOVjzhJqSClWwkKLlyM8pcSpitFgK6xoha4VIv9HarZG/ccmejNeilaXQaa5vPjIDbiYu/qMWycgzKm8NGcxt63qET59YT7RyZ0=,iv:iSDjkoSwXdXDV7/fIvv4/VcDisAKd+wT6U3GyS+0RjQ=,tag:P948brG9Vw59d92T3ZE9Ag==,type:str]
    pgp: []
    encrypted_regex: (hash|secret|password|encryption_key|accessKey)
    version: 3.7.1
