apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: v1.22.6
cloudProvider:
  gce: {}
  cloudConfig: |
    [global]
    regional = true
containerRuntime:
  containerd: {}
addons:
  enable: true
  path: "./addons"
  addons:
    - name: cluster-autoscaler
